/**
 * This is the root layout component in Next.js App Router.
 * @param children - The page content that will be rendered inside this layout
 */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Define metadata that will be used for SEO and browser tab information
export const metadata: Metadata = {
	title: "Create Next App", // Browser tab title
	description: "Generated by create next app", // Meta description for SEO
};

// Configure the Geist Sans & Mono font with CSS variables
const geistSans = Geist({
	variable: "--font-geist-sans", // CSS custom property name
	subsets: ["latin"], // Only load Latin characters to reduce bundle size
});
const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				id="layout"
				className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen w-screen`}
			>
				{/* Render the current page content */}
				{children}
			</body>
		</html>
	);
}
