import './globals.css';
import './layout.css';

import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

export const metadata: Metadata = {
	title: 'Create Next App', // Browser tab title
	description: 'Generated by create next app', // Meta description for SEO
};

const geistSans = Geist({
	variable: '--font-geist-sans', // CSS custom property name
	subsets: ['latin'], // Only load Latin characters to reduce bundle size
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				id="layout"
				className={`${geistSans.variable} ${geistMono.variable}`}
			>
				<header id="header"></header>
				<div id="content">{children}</div>
				<footer id="footer"></footer>
			</body>
		</html>
	);
}
